# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Messenger-App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messenger-App

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Kingfisher'
pod 'MessageKit'
pod 'JGProgressHUD'
pod 'Firebase/Database'



end
